include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**, "**/*.g.dart", "**/*.freezed.dart"]
  language:
    strict-raw-types: true
    strict-inference: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
exclude:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
